# build stage
FROM node:18-alpine AS builder

WORKDIR /gathercity

COPY ./package*.json ./
COPY ./turbo.json ./
COPY ./packages ./packages
COPY /apps/frontend ./apps/frontend

RUN npm install
RUN npm run build

# production stage
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=builder /gathercity/apps/frontend/dist/ ./
COPY ./apps/frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE  80

CMD [ "nginx", "-g", "daemon off;" ]
# CMD [ "npm", "run", "start:frontend" ]