FROM node:18-alpine

WORKDIR /usr/app/gathercity

COPY ./package*.json ./
COPY ./turbo.json ./
COPY ./apps/http ./apps/http
COPY ./packages ./packages

RUN npm install
RUN npm run db:generate
RUN npm run build

EXPOSE 3001

CMD [ "npm", "run", "start:http" ]