# build stage
FROM node:18-alpine AS builder

WORKDIR /gathercity

COPY ./package*.json ./
COPY ./turbo.json ./
COPY ./apps/frontend/package*.json ./frontend/package*.json
COPY ./packages ./packages

RUN npm install
COPY /apps/frontend ./frontend
RUN npm run build

# production stage
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=builder /gathercity/frontend/dist/ ./
COPY ./apps/frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE  80
CMD [ "nginx", "-g", "daemon off;" ]